### ISSUE TITLE
use as drop-in replacement for HASS-Deepstack-object component

### ISSUE THREAD

**Issue by thepiam** [robmarkcole/tensorflow-lite-rest-server#1]
Thank you so much for this repo - I got it working without any problems.
Hoping to use this as a drop-in replacement for the HASS-Deepstack-object component. 
I got errors as posted below. Probably due to differences in json formatting of the API response?

I am a total noob here. Tried to change codes in tflite-server.py to reformat json response but did not have any luck. Would really appreciate your suggestions. 
Thank you so much again.

**Errors from HASS log after HASS image-processing service call:** 
2020-01-25 07:50:28 ERROR (MainThread) [homeassistant.helpers.entity] Update for image_processing.person_detector_dafang fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 459, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/image_processing/__init__.py", line 135, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/deepstack_object/image_processing.py", line 168, in process_image
    self._dsobject.detect(image)
  File "/usr/local/lib/python3.7/site-packages/deepstack/core.py", line 127, in detect
    self._predictions = response.json()["predictions"]
KeyError: 'predictions'

**Errors from tensorflow-lite-rest-server terminal after HASS image-processing service call:**
Traceback (most recent call last):
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piam/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/piam/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/piam/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/piam/tensorflow-lite-rest-server/tflite-server.py", line 52, in predict
    interpreter.invoke()
  File "/home/piam/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 452, in invoke
    self._ensure_safe()
  File "/home/piam/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 272, in _ensure_safe
    data access.""")
RuntimeError: There is at least 1 reference to internal data
      in the interpreter in the form of a numpy array or slice. Be sure to
      only hold the function returned from tensor() if you are using raw
      data access.

**Comment by robmarkcole** [comment]
This app is returning data in a slightly different format, so cannot be substituted. I haven't decided what to do with this repo yet, but of course you could fork it and make changes as required

**Comment by thepiam** [comment]
thank you very much again
