### ISSUE TITLE
ERROR:    Exception in ASGI application

### ISSUE THREAD

**Issue by robmarkcole** [robmarkcole/tensorflow-lite-rest-server#37]
Getting:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/pi/.local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/pi/.local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
    instance = self.app(scope)
TypeError: __call__() missing 1 required positional argument: 'start_response'
```

I might have installed some new packages when working on flask branch, and since I am not using a venv this has caused a dependency crash?

**Comment by robmarkcole** [comment]
I was still on flask branch trying to run fastapi...
